bash scripts: holistically modified the system to use checker files

diff --git a/scripts/bash/cpr b/scripts/bash/cpr
--- a/scripts/bash/cpr
+++ b/scripts/bash/cpr
@@ -1,12 +1,21 @@
 # Bash Script for compiling and/or running cpp files
 
+<<COMMENT
+TODO:
+    -> view test case mode
+    -> checker handling done
+COMMENT
+
 ## Imports
 source helper.sh
 
 ## Cleanup when forcefully exiting execution
 function handle_ctrlc () {
     rm -f $file $file.out
-    rm -f in.ans
+    rm -f in.ans checker_input checker_output expected_output
+    if [[ $checker != *.cpp ]]; then
+        rm -f $checker
+    fi
     exit
 }
 trap handle_ctrlc SIGINT
@@ -27,6 +36,10 @@ input_test_mode=false
 clear_test_case=false
 help=false
 
+## Variables:
+folder=""
+checker=""
+
 POSITIONAL_ARGS=()
 
 while [[ $# -gt 0 ]]; do
@@ -35,7 +48,6 @@ while [[ $# -gt 0 ]]; do
         compile_mode=true
         debug=""
         shift # past argument
-        # shift # past value
         ;;
     -d|--debug)
         debug_mode=true
@@ -71,6 +83,16 @@ while [[ $# -gt 0 ]]; do
         debug=""
         shift # past argument
         ;;
+    -sf|--set-folder)
+        folder=$2
+        shift # past argument
+        shift # past value
+        ;;
+    -sc|--set-checker)
+        checker=$2
+        shift # past argument
+        shift # past value
+        ;;
     -h|--help)
         help=true
         shift # past argument
@@ -91,15 +113,17 @@ if [[ "$help" == true ]]; then
     echo "${BOLD}Usage:${RED_BOLD} cpr [options] <file_name>${CLEAR}"
     echo "${BOLD}file_name${CLEAR} assumes the extension .cpp if not given."
     echo "${BOLD}Options:"
-    echo " ${RED_BOLD} -c, --compile${CLEAR}  Compile the file"
-    echo " ${RED_BOLD} -d, --debug${CLEAR}    Compile the file with debug flag"
-    echo " ${RED_BOLD} -s, --silent${CLEAR}   Silences compilation warnings"
-    echo " ${RED_BOLD} -f, --final${CLEAR}    Compile and run the file without the debug flag"
-    echo " ${RED_BOLD} -t, --test${CLEAR}     Compile the file and run it against the saved test cases"
-    echo " ${RED_BOLD} -r, --run${CLEAR}      Compile the file and run it against a particular saved test case"
-    echo " ${RED_BOLD} -g, --gather${CLEAR}   Compile the file and run it. Save the input file for future testing. Ask for the output and save it too."
-    echo " ${RED_BOLD} -k, --clear${CLEAR}    Deletes the given test case"
-    echo " ${RED_BOLD} -h, --help${CLEAR}     Display this help message${CLEAR}"
+    echo " ${RED_BOLD} -c, --compile${CLEAR}       Compile the file"
+    echo " ${RED_BOLD} -d, --debug${CLEAR}         Compile the file with debug flag"
+    echo " ${RED_BOLD} -s, --silent${CLEAR}        Silences compilation warnings"
+    echo " ${RED_BOLD} -f, --final${CLEAR}         Compile and run the file without the debug flag"
+    echo " ${RED_BOLD} -t, --test${CLEAR}          Compile the file and run it against the saved test cases"
+    echo " ${RED_BOLD} -r, --run${CLEAR}           Compile the file and run it against a particular saved test case"
+    echo " ${RED_BOLD} -g, --gather${CLEAR}        Compile the file and run it. Save the input file for future testing. Ask for the output and save it too."
+    echo " ${RED_BOLD} -k, --clear${CLEAR}         Deletes the given test case"
+    echo " ${RED_BOLD} -sf, --set-folder${CLEAR}   Set test folder name"
+    echo " ${RED_BOLD} -sc, --set-checker${CLEAR}  Set checker path"
+    echo " ${RED_BOLD} -h, --help${CLEAR}          Display this help message${CLEAR}"
     exit
 fi
 
@@ -109,6 +133,30 @@ set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters
 if [[ $# -eq 0 ]]; then file="file"; file_loc="file.cpp";
 else file=`basename $1 .cpp`; file_loc=$1; fi
 rm -f $file $file.out
+
+if [[ $folder == "" ]]; then
+    folder="test_${file}"
+else
+    if [[ $folder != test_* ]]; then
+        echo "${RED_BOLD}ERROR:${CLEAR} Incorrect test folder name ${folder}."
+        exit
+    fi
+fi
+
+if [[ $checker == "" ]]; then
+    checker="./test_${file}/checker.cpp"
+    if ! test -f $checker; then
+        checker=""
+    fi
+else
+    if ! test -f $checker; then
+        echo "${RED_BOLD}ERROR:${CLEAR} Given checker file ${checker} does not exist."
+        exit
+    elif [[ $checker != *.cpp ]]; then
+        echo "${RED_BOLD}ERROR: ${checker}${CLEAR} is not a cpp file."
+        exit
+    fi
+fi
 
 # If file does not exist then exit
 if [[ $file_loc != *.cpp ]]; then file_loc=${file_loc}.cpp; fi
@@ -198,11 +246,21 @@ if [[ "$input_test_mode" == true ]]; then
     fi
 fi
 
+## Gathering Mode (0/1):
+if [[ "$gather_mode" == true ]]; then
+    echo "${BOLD}Enter input:${CLEAR}"
+fi
+
 # Compiling
 g++ -std=c++20 $file_loc -o $file $debug $warnings $flags
 
 ## If only need to compile, then exit
 if [[ "$compile_mode" == true || "$debug_mode" == true ]]; then exit; fi
+
+if [[ $checker != "" ]]; then
+    cpr $checker --compile
+    checker=`basename $checker .cpp`
+fi
 
 ## Testing Mode:
 if [[ "$test_mode" == true ]]; then
@@ -215,7 +273,7 @@ if [[ "$test_mode" == true ]]; then
             rm -rvf output_$file
             break
         fi
-        echo $input
+        printf '%s' "${input}: "
         outfile=`basename $input`
         outfile=${outfile%".in"}.ans
         if ! test -f output_$file/$outfile; then
@@ -223,10 +281,29 @@ if [[ "$test_mode" == true ]]; then
             continue
         fi
         ./$file < $input > in.ans
-        diff -w in.ans output_$file/$outfile || break
+        if [[ $checker != "" ]]; then
+            (echo "${OUTPUT_START}" && echo $input && echo "${OUTPUT_END}" && echo "${OUTPUT_START}" && cat in.ans && echo "${OUTPUT_END}" && echo "${OUTPUT_START}" && cat output_$file/$outfile && echo "${OUTPUT_END}") > checker_input
+            ./$checker < checker_input > checker_output
+            echo "Yes" > expected_output
+            diff -w checker_output expected_output &>/dev/null
+        else
+            diff -w in.ans output_$file/$outfile &>/dev/null
+        fi
+        if [ $? -eq 0 ]; then
+            echo "${GREEN_BOLD}AC${CLEAR}"
+        else
+            echo "${RED_BOLD}WA${CLEAR}"
+            echo "${BOLD}\nFailing Input:${CLEAR}"
+            echo $input
+            echo "${BOLD}\noutput begins now:${CLEAR}"
+            cat in.ans
+            echo "${GREEN_BOLD}\ncorrect output:${CLEAR}"
+            cat output_$file/$outfile
+            break
+        fi
         rm -f in.ans
     done
-    rm -f $file $file.out
+    handle_ctrlc
     exit
 fi
 
@@ -235,11 +312,12 @@ if [[ "$input_test_mode" == true ]]; then
     echo $input
     cat $input
     ./$file < $input > $file.out
-    echo "\noutput begins now:"
+    echo "${BOLD}\noutput begins now:${CLEAR}"
     cat $file.out
     rm -f $file $file.out
-    echo "\ncorrect output:"
+    echo "${GREEN_BOLD}\ncorrect output:${CLEAR}"
     cat $outfile
+    handle_ctrlc
     exit
 fi
 
@@ -261,21 +339,33 @@ then
     ct="$(sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'<<<"$ct")"
     echo "$input" > $file$ct.in
     ./$file < $file$ct.in > $file.out
-    echo "my output begins now:"
+    echo "${BOLD}output begins now:${CLEAR}"
     cat $file.out
-    echo "\nInput the correct output:"
+    echo "${BOLD}\nInput the correct output:${CLEAR}"
     output=$(sed '/^$/q')
     echo "$output" > $file$ct.ans
-    diff -w $file.out $file$ct.ans || echo "Output does not match."
+    if [[ $checker != "" ]]; then
+        (echo "${OUTPUT_START}" && cat $file$ct.in && echo "${OUTPUT_END}" && echo "${OUTPUT_START}" && cat $file.out && echo "${OUTPUT_END}" && echo "${OUTPUT_START}" && cat $file$ct.ans && echo "${OUTPUT_END}") > checker_input
+        ./$checker < checker_input > checker_output
+        echo "Yes" > expected_output
+        diff -w checker_output expected_output &>/dev/null
+    else
+        diff -w $file.out $file$ct.ans &>/dev/null
+    fi
+    if [ $? -eq 0 ]; then
+        echo "${GREEN_BOLD}AC${CLEAR}"
+    else
+        echo "${RED_BOLD}WA${CLEAR}"
+    fi
     sdir $file
-    rm -f $file $file.out
+    handle_ctrlc
     exit
 fi
 
 ## Finally run the program
 if test -f $file; then
     ./$file > $file.out
-    echo "\noutput begins now:"
+    echo "${BOLD}\noutput begins now:${CLEAR}"
     cat $file.out
     rm $file $file.out
 fi
diff --git a/scripts/bash/rtest b/scripts/bash/rtest
--- a/scripts/bash/rtest
+++ b/scripts/bash/rtest
@@ -1,7 +1,5 @@
 ## Script to test the solution against brute force solution with generator cpp providing the inputs
 
-# set -e
-
 <<COMMENT
 TODO:
     -> Checker
@@ -12,8 +10,15 @@ COMMENT
 ## Imports:
 source helper.sh
 
+## File names:
+opt_sol="__NA__"
+checker="checker"
+brute_force="brute_force"
+generator="generator"
+
 ## Modes:
 vs_brute_force=true # Assumed in general
+
 explore_mode=false
 debug_mode=false
 test_mode=false
@@ -21,8 +26,11 @@ case_mode=false
 manual_mode=false
 save_mode=false
 help=false
+
+# Unimplemented
 checker_mode=false
 tle_mode=false
+
 
 POSITIONAL_ARGS=()
 
@@ -65,6 +73,26 @@ while [[ $# -gt 0 ]]; do
         checker_mode=true
         shift # past argument
         ;;
+    -ss|--set_solution)
+        opt_sol=$2
+        shift # past argument
+        shift # past value
+        ;;
+    -sg|--set_generator)
+        generator=$2
+        shift # past argument
+        shift # past value
+        ;;
+    -sb|--set_brute_force)
+        brute_force=$2
+        shift # past argument
+        shift # past value
+        ;;
+    -sc|--set_checker)
+        checker=$2
+        shift # past argument
+        shift # past value
+        ;;
     -h|--help)
         help=true
         explore_mode=false
@@ -102,12 +130,6 @@ fi
 
 set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters
 
-
-opt_sol=${1:-"__NA__"}
-checker=${2:-"none"}
-brute_force=${3:-"brute_force"}
-generator=${4:-"generator"}
-
 if [[ $opt_sol == "__NA__" ]]; then
     opt_sol=`basename $PWD`
     opt_sol=${opt_sol#"test_"}.cpp
@@ -124,12 +146,13 @@ brute_force=$(fixname $brute_force)
 generator=$(fixname $generator)
 
 function exists {
-    if ! test -f $2/$1.cpp; then echo "$1.cpp does not exist"; exit 1; fi
+    if ! test -f $2/$1.cpp; then
+        echo "${RED_BOLD}$1.cpp${CLEAR} does not exist."
+        exit 1
+    fi
 }
 exists $opt_sol ..
-if [[ $checker != "none" ]]; then 
-    exists $checker .
-fi
+exists $checker .
 exists $brute_force .
 exists $generator .
 
@@ -137,7 +160,8 @@ function handle_ctrlc(){
     rm -f $generator
     rm -f $brute_force
     rm -f $opt_sol
-    rm -f input out1 out2
+    rm -f $checker
+    rm -f input out1 out2 checker_input out3 out4
     exit
 }
 trap handle_ctrlc SIGINT
@@ -207,28 +231,29 @@ if [[ "$case_mode" == true ]]; then
         echo "Cannot have${RED_BOLD} manual${CLEAR} option enabled with${RED_BOLD} case${CLEAR} mode"
         exit
     fi
-    echo "${BOLD}Testing ${RED_BOLD}$opt_sol.cpp${CLEAR}${BOLD} against ${RED_BOLD}${brute_force}.cpp${CLEAR}${BOLD} on a randomly generated input by ${RED_BOLD}${generator}.cpp${CLEAR}"
+    echo "${BOLD}Testing ${RED_BOLD}$opt_sol.cpp${CLEAR}${BOLD} against ${RED_BOLD}${brute_force}.cpp${CLEAR}${BOLD} on a randomly generated input by ${RED_BOLD}${generator}.cpp${CLEAR} using ${RED_BOLD}${checker}.cpp${CLEAR}."
     cpr ../$opt_sol.cpp $compile_mode
-    if [[ $checker != "none" ]]; then cpr $checker.cpp --compile; fi
-    cpr $brute_force --compile
+    cpr $checker.cpp --compile
+    cpr $brute_force.cpp --compile
     cpr $generator.cpp --compile
     ./generator > input
     ./$opt_sol < input > out1
     ./$brute_force < input > out2
+    (echo "${OUTPUT_START}" && cat input && echo "${OUTPUT_END}" && echo "${OUTPUT_START}" && cat out1 && echo "${OUTPUT_END}" && echo "${OUTPUT_START}" && cat out2 && echo "${OUTPUT_END}") > checker_input
     echo "${BOLD}Input:${CLEAR}"
     cat input
     echo "${BOLD}\noutput begins now:${CLEAR}"
     cat out1
-    echo "${BOLD}\ncorrect output:${CLEAR}"
+    echo "${GREEN_BOLD}\ncorrect output:${CLEAR}"
     cat out2
-    if [[ $checker != "none" ]]; then
-        cat input out1 > in1
-        cat input out2 > in2
-        ./$checker < in1 > out1
-        ./$checker < in2 > out2
-        rm -f in1 in2
+    ./$checker < checker_input > out3
+    echo "Yes" > out4
+    diff -w out3 out4 &>/dev/null
+    if [ $? -eq 0 ]; then
+        echo "\n${GREEN_BOLD}AC${CLEAR}"
+    else
+        echo "\n${RED_BOLD}WA${CLEAR}"
     fi
-    diff -w out1 out2 || echo "Output does not match."
     if [[ "$save_mode" == false ]]; then handle_ctrlc; exit; fi
     copy_input $opt_sol ..
     cd test_$opt_sol
@@ -239,27 +264,29 @@ fi
 
 # Manual Mode:
 if [[ "$manual_mode" == true ]]; then
-    echo "${BOLD}Testing ${RED}${opt_sol}.cpp${CLEAR}${BOLD} against ${RED}${brute_force}.cpp${CLEAR}${BOLD} on given manual input.${CLEAR}"
+    echo "${BOLD}Testing ${RED}${opt_sol}.cpp${CLEAR}${BOLD} against ${RED}${brute_force}.cpp${CLEAR}${BOLD} using ${RED}${checker}${CLEAR}${BOLD} on given manual input.${CLEAR}"
     echo "${BOLD}Enter input:${CLEAR}"
     input=$(sed '/^$/q')
     echo "$input" > input
     cpr ../$opt_sol.cpp $compile_mode
     if [[ $checker != "none" ]]; then cpr $checker.cpp --compile; fi
     cpr $brute_force --compile
+    cpr $checker --compile
     ./$opt_sol < input > out1
     ./$brute_force < input > out2
     echo "${BOLD}\noutput begins now:${CLEAR}"
     cat out1
-    echo "${BOLD}\ncorrect output:${CLEAR}"
+    echo "${GREEN_BOLD}\ncorrect output:${CLEAR}"
     cat out2
-    if [[ $checker != "none" ]]; then
-        cat input out1 > in1
-        cat input out2 > in2
-        ./$checker < in1 > out1
-        ./$checker < in2 > out2
-        rm -f in1 in2
+    (echo "${OUTPUT_START}" && cat input && echo "${OUTPUT_END}" && echo "${OUTPUT_START}" && cat out1 && echo "${OUTPUT_END}" && echo "${OUTPUT_START}" && cat out2 && echo "${OUTPUT_END}") > checker_input
+    ./$checker < checker_input > out3
+    echo "Yes" > out4
+    diff -w out3 out4 &>/dev/null
+    if [ $? -eq 0 ]; then
+        echo "\n${GREEN_BOLD}AC${CLEAR}"
+    else
+        echo "\n${RED_BOLD}WA${CLEAR}"
     fi
-    diff -w out1 out2 || echo "Output does not match."
     if [[ "$save_mode" == false ]]; then handle_ctrlc; exit; fi
     copy_input $opt_sol ..
     cd test_$opt_sol
@@ -268,33 +295,35 @@ if [[ "$manual_mode" == true ]]; then
     exit
 fi
 
-echo "Testing ${RED_BOLD}${opt_sol}.cpp${CLEAR} against ${RED_BOLD}${brute_force}.cpp${CLEAR} with ${RED_BOLD}${generator}.cpp${CLEAR}"
+echo "Testing ${RED_BOLD}${opt_sol}.cpp${CLEAR} against ${RED_BOLD}${brute_force}.cpp${CLEAR} with ${RED_BOLD}${generator}.cpp${CLEAR} using ${RED_BOLD}${checker}.cpp${CLEAR}."
 
 cpr ../$opt_sol.cpp --compile
-if [[ $checker != "none" ]]; then cpr $checker.cpp --compile; fi
+cpr $checker.cpp --compile
 cpr $brute_force.cpp --compile
 cpr $generator.cpp --compile
 
 for((i=1;;++i));do
-    echo $i
+    printf '%s' "${i}: "
     # Call generator and pipe to input
     ./$generator > input
     ./$opt_sol < input > out1
     ./$brute_force < input > out2
-    if [[ $checker != "none" ]]; then
-        cat input out1 > in1
-        cat input out2 > in2
-        ./$checker < in1 > out1
-        ./$checker < in2 > out2
-        rm -f in1 in2
+    (echo "${OUTPUT_START}" && cat input && echo "${OUTPUT_END}" && echo "${OUTPUT_START}" && cat out1 && echo "${OUTPUT_END}" && echo "${OUTPUT_START}" && cat out2 && echo "${OUTPUT_END}") > checker_input
+    ./$checker < checker_input > out3
+    echo "Yes" > out4
+    diff -w out3 out4 &>/dev/null
+    if [ $? -eq 0 ]; then
+        echo "${GREEN_BOLD}AC${CLEAR}"
+    else
+        echo "${RED_BOLD}WA${CLEAR}"
+        break
     fi
-    diff -w out1 out2 || break
 done
-echo "${UNDERLINE}${RED_BOLD}\nFailing input:${CLEAR}"
+echo "${BOLD}\nFailing input:${CLEAR}"
 cat input
-echo "${UNDERLINE}${RED_BOLD}\noutput begins now:${CLEAR}"
+echo "${BOLD}\noutput begins now:${CLEAR}"
 cat out1
-echo "${UNDERLINE}${RED_BOLD}\ncorrect output:${CLEAR}"
+echo "${GREEN_BOLD}\ncorrect output:${CLEAR}"
 cat out2
 copy_input $opt_sol ..
 cd test_$opt_sol
diff --git a/scripts/bash/stest b/scripts/bash/stest
--- a/scripts/bash/stest
+++ b/scripts/bash/stest
@@ -1,38 +1,114 @@
 ## Script for setting up a testing folder for the given problem
 
-## Imports
+## Imports:
 source helper.sh
 
-folder_name=${1:-"test"}
+POSITIONAL_ARGS=()
+help=false
+folder_name="test"
+generator="generator.cpp"
+brute_force="brute_force.cpp"
+checker="checker.cpp"
+
+while [[ $# -gt 0 ]]; do
+    case $1 in
+        -h|--help)
+            help=true
+            shift # past argument
+            ;;
+        -f|--folder)
+            folder_name=$2
+            shift # past argument
+            shift # past value
+            ;;
+        -g|--generator)
+            generator=$2
+            shift # past argument
+            shift # past value
+            ;;
+        -b|--brute_force)
+            brute_force=$2
+            shift # past argument
+            shift # past value
+            ;;
+        -c|--checker)
+            checker=$2
+            shift # past argument
+            shift # past value
+            ;;
+        -*|--*)
+            echo "${RED_BOLD}ERROR:${CLEAR} Unknown option ${RED_BOLD}$1${CLEAR}"
+            stest -h
+            exit
+            ;;
+        *)
+            POSITIONAL_ARGS+=("$1") # save positional arg
+            shift # past argument
+            ;;
+    esac
+done
+
+set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters
+
 opt_sol=${1:-"test.cpp"}
-if [[ $opt_sol != *.cpp ]]
-then
+
+if [[ "$help" == true ]]; then
+    echo "${RED_BOLD}stest${CLEAR} is a script to set up the testing system for a given cpp file ${RED_BOLD}cpp_file.cpp${CLEAR}. By default, creates a ${RED_BOLD}test_<cpp_file>${CLEAR} sub-directory and creates ${RED_BOLD}[generator].cpp${CLEAR}, ${RED_BOLD}[brute_force].cpp${CLEAR} and ${RED_BOLD}[checker].cpp${CLEAR} inside it."
+    echo "${BOLD}Usage:${RED_BOLD} stest cpp_file [options]${CLEAR}"
+    echo "${BOLD}Options:"
+    echo " ${RED_BOLD} -f, --folder       folder_name${CLEAR}   Set the suffix of the test folder name"
+    echo " ${RED_BOLD} -g, --generator    generator${CLEAR}     Set the generator file name"
+    echo " ${RED_BOLD} -g, --brute_force  brute_force${CLEAR}   Set the brute_force file name"
+    echo " ${RED_BOLD} -c, --checker      checker${CLEAR}       Set the brute_force file name"
+    echo " ${RED_BOLD} -h, --help${CLEAR}                       Display this help message"
+    exit
+fi
+
+if [[ $opt_sol != *.cpp ]]; then
     opt_sol="$opt_sol.cpp"
 fi
-if ! test -f $opt_sol
-then
+if ! test -f $opt_sol; then
   echo "${opt_sol} does not exist."
   exit 1
 fi
-if [[ $folder_name == *.cpp ]]
-then
+if [[ $folder_name == *.cpp ]]; then
     folder_name=${folder_name%".cpp"}
 fi
-if ! test -f $TEST_CASE_GENERATOR
-then
+if ! test -f $TEST_CASE_GENERATOR; then
     echo "${RED_BOLD}${TEST_CASE_GENERATOR}${CLEAR} does not exist."
     exit
 fi
-if ! test -f $BRUTE_FORCE
-then
+if ! test -f $BRUTE_FORCE; then
     echo "${RED_BOLD}${BRUTE_FORCE}${CLEAR} does not exist."
     exit
 fi
+if ! test -f $CHECKER; then
+    echo "${RED_BOLD}${CHECKER}${CLEAR} does not exist."
+    exit
+fi
 folder_name="test_${folder_name}"
-echo "Setting up testing folder for ${opt_sol} as ${folder_name}"
 mkdir -p $folder_name
+if [ -f $folder_name/$generator ] && [ -f $folder_name/$brute_force ] && [ -f $folder_name/$checker ]; then
+    echo "Testing system already exists for ${RED_BOLD}${opt_sol}${CLEAR}."
+    exit
+fi
+echo "Setting up testing system for ${opt_sol} as ${folder_name}"
+created=$(date)
+echo $created
 cd $folder_name
-cp -n $TEST_CASE_GENERATOR ./
-cp -n $BRUTE_FORCE ./
-code brute_force.cpp
-code generator.cpp
+cp -n $TEST_CASE_GENERATOR ./$generator
+cp -n $BRUTE_FORCE ./$brute_force
+cp -n $CHECKER ./$checker
+sed -i '' '4i\
+* Created : '"${created}"'\
+' $generator
+sed -i '' '4i\
+* Created : '"${created}"'\
+' $brute_force
+sed -i '' '4i\
+* Created : '"${created}"'\
+' $checker
+
+code $checker
+code $brute_force
+code $generator
